### ISSUE TITLE
この repo は何ですか？

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-ci-example#4]
example ということですが、 example も細かく分ければいろいろあるはずです。
「clone すればそのまま使えるテンプレート」か「いろんな設定例を含んでいるデモ集」のどちらかかなと思っていますが、どちらでしょうか？

**Comment by yosupo06** [comment]
後者です　このリポジトリをそのままテンプレートとして使うことは想定していません

具体的に動くものを一式用意しておくことで、CIの設定ファイルでの消耗を減らせないかと考えています。特に競プロライブラリにCIを組み込もうとする人の多くは、CI自体を使うのが初めてだと予想しているので

**Comment by kmyk** [comment]
なるほど。ありがとうございます
